### ISSUE TITLE
Housing market analysis - Employment and job trends

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#57]
Produce data tables in Excel on demographic trends in the RHF-defined Washington region.

**Needed by: Feb 22.**

- Jobs for Washington MSA (not RHF-defined region) compared to other large MSAs, 1990 - 2017 [a]
- Jobs by private, federal gov't, local/state gov't, 1990 - 2017 [a]
- Private sector jobs by industry, 1990 - 2017 [a]
- Adults by employment status (civilian employed, in military, students, unemployed, not in labor force), 2000, 2010, 2017 [b]
- Civilian full-time, year-round employed workers by wage (low, middle, high), 2000, 2010, 2017 [b]

Data sources: [a] BLS (adapt **L:\Libraries\Requests\Prog\2018\Washington region feature\compile BLS data.sas**); [b] IPUMS Census/ACS.

Notes:
- All data are counts (numbers of jobs, workers) for the entire region unless other specified.
- Years should define table columns; other dimension are rows.
- Always include a total row in the table. 
- For the other large MSAs, use
  - Atlanta-Sandy Springs-Roswell
  - Boston-Cambridge-Nashua
  - Chicago-Naperville-Elgin
  - Dallas-Fort Worth-Arlington
  - Detroit-Warren-Dearborn
  - Houston-The Woodlands-Sugar Land
  - Los Angeles-Long Beach-Anaheim
  - Miami-Fort Lauderdale-West Palm Beach
  - Minneapolis-St. Paul-Bloomington
  - New York-Newark-Jersey City
  - Philadelphia-Camden-Wilmington
  - Phoenix-Mesa-Scottsdale
  - San Francisco-Oakland-Hayward
  - Seattle-Tacoma-Bellevue
- For wages, use the following definitions.
  - Full-time is 35+ hours worked per week
  - Year-round is 50-52 weeks worked per year
  - High wage is >= 1.5 * average annual wage/salary inc for civilian ft/yr-rnd workers in region in that year
  - Low wage is <= 0.5 * average annual wage/salary inc for civilian ft/yr-rnd workers in region in that year

**Comment by rpitingolo** [comment]
@ptatian can you please review Employment Trends.sas which are the BLS data indicators. There are some weird  things going on. 

On sectorjobs_byyear there are no reported jobs in state and local government in any years. The big file even shows establishment counts but no employment counts for state and local government. I'm not sure what's going on there. 

On industryjobs_byyear, the trend seems reasonable (have there really been 750k new jobs added since 1990?) but the actual numbers by naics code seem off. For example construction jumps from zero to 174k then back down to zero. I also can't get the numbers to sum up to the total, even when taking out the 101 and 102 naics codes. Any ideas?

**Comment by rpitingolo** [comment]
L:\Libraries\RegHsg\Prog\Employment Trends.log
L:\Libraries\RegHsg\Prog\iPums Employment Trends.log
